//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B_SiteListing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.tblCompanyIPOes = new HashSet<tblCompanyIPO>();
        }
    
        public long CompanyId { get; set; }
        public Nullable<long> ContactId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyDiscription { get; set; }
        public string CompanyKeyword { get; set; }
        public string CompanyOwner { get; set; }
        public string CompanayEstablishedyear { get; set; }
        public Nullable<long> ComapanyTotalEmployees { get; set; }
        public Nullable<long> CompanyAnnualInCome { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public string companyGST { get; set; }
        public string City { get; set; }
        public string state { get; set; }
        public string CompanyCountry { get; set; }
        public string compapprovalbody { get; set; }
        public string Uploadlogo { get; set; }
        public string UploadcompanyphotoOn { get; set; }
    
        public virtual EnquiryContact EnquiryContact { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCompanyIPO> tblCompanyIPOes { get; set; }
    }
}
