//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B_SiteListing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryMaster
    {
        public int CountryId { get; set; }
        public string CountryName { get; set; }
        public string ISO_Names { get; set; }
        public Nullable<int> Country_ISD_Code { get; set; }
    }
}
