//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B_SiteListing.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class B2BprojectDataEntities : DbContext
    {
        public B2BprojectDataEntities()
            : base("name=B2BprojectDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BussinessType> BussinessTypes { get; set; }
        public virtual DbSet<BuyerDetail> BuyerDetails { get; set; }
        public virtual DbSet<CategoriesType> CategoriesTypes { get; set; }
        public virtual DbSet<CitiMaster> CitiMasters { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyBusiness> CompanyBusinesses { get; set; }
        public virtual DbSet<CountryMaster> CountryMasters { get; set; }
        public virtual DbSet<EnquiryContact> EnquiryContacts { get; set; }
        public virtual DbSet<NewProductLaunch> NewProductLaunches { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<StateMaster> StateMasters { get; set; }
        public virtual DbSet<tblCompanyIPO> tblCompanyIPOes { get; set; }
        public virtual DbSet<tblEvent> tblEvents { get; set; }
        public virtual DbSet<tblHospital> tblHospitals { get; set; }
        public virtual DbSet<tblNew> tblNews { get; set; }
        public virtual DbSet<UserRoleMapping> UserRoleMappings { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
