//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B_SiteListing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewProductLaunch
    {
        public long Id { get; set; }
        public string ProductName { get; set; }
        public string ProductType { get; set; }
        public string ProductPhoto { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> updatedBy { get; set; }
        public Nullable<long> businessId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<long> CategoryTypeId { get; set; }
    
        public virtual BussinessType BussinessType { get; set; }
        public virtual CategoriesType CategoriesType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
