//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B_SiteListing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEvent
    {
        public long Id { get; set; }
        public Nullable<long> BusinessId { get; set; }
        public string EventName { get; set; }
        public string EventDiscription { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string EventLocation { get; set; }
        public string EventImage { get; set; }
        public string EventVideo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CountryName { get; set; }
        public string StateName { get; set; }
        public string CityName { get; set; }
        public string EventVenue { get; set; }
        public Nullable<bool> IsRegistrationOpen { get; set; }
        public string ShowInsterast { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> EventStatus { get; set; }
    
        public virtual BussinessType BussinessType { get; set; }
        public virtual User User { get; set; }
    }
}
