//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B_SiteListing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHospital
    {
        public long Id { get; set; }
        public Nullable<int> HospitalOperation { get; set; }
        public string parentcountry { get; set; }
        public string parentHospitalName { get; set; }
        public string HospitalName { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string HospitalAddress { get; set; }
        public string HospitalWebSite { get; set; }
        public Nullable<int> ISDCodes { get; set; }
        public string PhoneNumber { get; set; }
        public string HospitalGST { get; set; }
        public string HospitalApprovedBody { get; set; }
        public string UploadLogo { get; set; }
        public string UploadHospitalPhoto { get; set; }
        public string HospitalActivities { get; set; }
        public Nullable<int> HospitalType { get; set; }
        public string HospitalCapacity { get; set; }
        public string HospitalTurnover { get; set; }
        public string HospitalEmployee { get; set; }
        public Nullable<System.DateTime> Hospitalestablishment { get; set; }
        public string Associationmember { get; set; }
        public string SellingKeywords { get; set; }
        public string HospitalDescription { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
